name: Generate 3D Contribution Graph

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # roda diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/Github-Profile-3D-Contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: PedroElorriaga

      - name: Commit and push generated SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add profile-3d-contrib/*.svg
          git commit -m "Update 3D contribution graph" || echo "No changes to commit"
          git push
